/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprint3;

import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class Arrange extends javax.swing.JFrame {

    /**
     * Creates new form Arrange
     */
    public Arrange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMenu = new javax.swing.JTable();
        jcbArrange = new javax.swing.JComboBox<>();
        jbtnArrange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        jtbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Milo Ais", "2.30", "Drinks", "asd"},
                {"Ham burger", "4.00", "Food", "asd"},
                {"Nasi Lemak Ayam", "5.00", "Food", "asd"},
                {"Nasi Goreng", "5.50", "Food", "asd"},
                {"Kopi Ais", "2.00", "Drinks", "sad"},
                {"Mee Goreng", "5.00", "Food", "asd"},
                {"Nescafe", "2.50", "Drinks", "asd"},
                {"Apple juice", "4.00", "Drinks", "asd"},
                {"Carrot Milk", "4.50", "Drinks", "asd"},
                {"Nasi Goreng Pattaya", "6.00", "Food", "asd"},
                {"Nasi Goreng USA", "6.50", "Food", "asd"},
                {"Roti Canai", "0.80", "Food", "asd"},
                {"Roti Telur", "1.70", "Food", "asd"},
                {"Roti Planta", "1.50", "Food", "asd"},
                {"Teh Ice", "1.50", "Drinks", "asd"}
            },
            new String [] {
                "Food Name", "Price", "Category", "Details"
            }
        ));
        jScrollPane1.setViewportView(jtbMenu);

        jcbArrange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Name-Asc", "Food Name-Desc", "Price/Category - Asc", "Price/Category - Desc", " ", " " }));

        jbtnArrange.setText("Arrange");
        jbtnArrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnArrangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnArrange)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jcbArrange, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbArrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jbtnArrange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnArrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnArrangeActionPerformed
        if (jcbArrange.getSelectedIndex() == 0) {
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jtbMenu.getModel());
            jtbMenu.setRowSorter(sorter);
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();

            int columnIndexToSort = 0;
            sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));

            sorter.setSortKeys(sortKeys);
            sorter.sort();
        } else if (jcbArrange.getSelectedIndex() == 1) {
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jtbMenu.getModel());
            jtbMenu.setRowSorter(sorter);
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();

            int columnIndexToSort = 0;
            sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.DESCENDING));

            sorter.setSortKeys(sortKeys);
            sorter.sort();
        } else if (jcbArrange.getSelectedIndex() == 2) {
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jtbMenu.getModel());
            jtbMenu.setRowSorter(sorter);
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();

            int columnIndexForCategory = 2;
            sortKeys.add(new RowSorter.SortKey(columnIndexForCategory, SortOrder.ASCENDING));
            
            int columnIndexForPrice = 1;
            sortKeys.add(new RowSorter.SortKey(columnIndexForPrice, SortOrder.ASCENDING));

            sorter.setSortKeys(sortKeys);
            sorter.sort();
        } else if (jcbArrange.getSelectedIndex() == 3) {
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jtbMenu.getModel());
            jtbMenu.setRowSorter(sorter);
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();

            int columnIndexForCategory = 2;
            sortKeys.add(new RowSorter.SortKey(columnIndexForCategory, SortOrder.ASCENDING));
            
            int columnIndexForPrice = 1;
            sortKeys.add(new RowSorter.SortKey(columnIndexForPrice, SortOrder.DESCENDING));

            sorter.setSortKeys(sortKeys);
            sorter.sort();
        }
    }//GEN-LAST:event_jbtnArrangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arrange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnArrange;
    private javax.swing.JComboBox<String> jcbArrange;
    private javax.swing.JTable jtbMenu;
    // End of variables declaration//GEN-END:variables
}
