
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class DM_DailyReport extends javax.swing.JFrame {

    /**
     * Creates new form DM_DailyReport
     */
    public DM_DailyReport() {
        initComponents();
        Date();
        staff();
    }

    public void Date() {
        Date today = Calendar.getInstance().getTime();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        String date = s.format(today);
        jtfDate.setText(date);

    }
    
    private void staff(){
        jtfStaffID.setText("ST001");
        jtfStaffName.setText("Jack");
        jtfTDT.setText("120");
        jtfTDC.setText("35");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblDateTime1 = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        jlblDateTime2 = new javax.swing.JLabel();
        jtfStaffID = new javax.swing.JTextField();
        jlblDateTime3 = new javax.swing.JLabel();
        jtfStaffName = new javax.swing.JTextField();
        jlblDateTime4 = new javax.swing.JLabel();
        jlblDateTime5 = new javax.swing.JLabel();
        jtfTDC = new javax.swing.JTextField();
        jbtnConfirm = new javax.swing.JButton();
        jlblStaffName1 = new javax.swing.JLabel();
        jtfTDT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Daily Delivery Report");

        jlblDateTime1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime1.setText("Staff ID :");

        jtfDate.setEditable(false);
        jtfDate.setBackground(java.awt.Color.lightGray);
        jtfDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblDateTime2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime2.setText("Staff Name :");

        jtfStaffID.setEditable(false);
        jtfStaffID.setBackground(java.awt.Color.lightGray);
        jtfStaffID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblDateTime3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime3.setText("Total distance travelled :");

        jtfStaffName.setEditable(false);
        jtfStaffName.setBackground(java.awt.Color.lightGray);
        jtfStaffName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblDateTime4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime4.setText("Total delivery completed :");

        jlblDateTime5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime5.setText("Date :");

        jtfTDC.setEditable(false);
        jtfTDC.setBackground(java.awt.Color.lightGray);
        jtfTDC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jbtnConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnConfirm.setText("Confirm");
        jbtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmActionPerformed(evt);
            }
        });

        jlblStaffName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblStaffName1.setText("KM");

        jtfTDT.setEditable(false);
        jtfTDT.setBackground(java.awt.Color.lightGray);
        jtfTDT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblDateTime3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jbtnConfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDateTime2)
                            .addComponent(jlblDateTime1)
                            .addComponent(jlblDateTime5)
                            .addComponent(jlblDateTime4))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfTDC, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblStaffName1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDateTime5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDateTime1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDateTime2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDateTime3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblStaffName1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDateTime4)
                    .addComponent(jtfTDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jbtnConfirm)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DM_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DM_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DM_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DM_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DM_DailyReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnConfirm;
    private javax.swing.JLabel jlblDateTime1;
    private javax.swing.JLabel jlblDateTime2;
    private javax.swing.JLabel jlblDateTime3;
    private javax.swing.JLabel jlblDateTime4;
    private javax.swing.JLabel jlblDateTime5;
    private javax.swing.JLabel jlblStaffName1;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JTextField jtfStaffName;
    private javax.swing.JTextField jtfTDC;
    private javax.swing.JTextField jtfTDT;
    // End of variables declaration//GEN-END:variables
}
