
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class HR_DailyReport extends javax.swing.JFrame {

    /**
     * Creates new form HR_DailyReport
     */
    public HR_DailyReport() {
        initComponents();
        Date();
        staffID();
    }

    public void Date() {
        Date today = Calendar.getInstance().getTime();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        String date = s.format(today);
        jtfDate.setText(date);
    }


    private void staffID() {
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfStaffName = new javax.swing.JTextField();
        jlblTDT = new javax.swing.JLabel();
        jtfTDT = new javax.swing.JTextField();
        jlblTDC = new javax.swing.JLabel();
        jtfTDC = new javax.swing.JTextField();
        jlblDateTime5 = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlblDateTime1 = new javax.swing.JLabel();
        jbtnCheck = new javax.swing.JButton();
        jlblStaffName = new javax.swing.JLabel();
        jcbStaffID = new javax.swing.JComboBox();
        jlblStaffName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfStaffName.setEditable(false);
        jtfStaffName.setBackground(java.awt.Color.lightGray);
        jtfStaffName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblTDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTDT.setText("Total distance travelled(daily) :");

        jtfTDT.setEditable(false);
        jtfTDT.setBackground(java.awt.Color.lightGray);
        jtfTDT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblTDC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTDC.setText("Total delivery completed(daily) :");

        jtfTDC.setEditable(false);
        jtfTDC.setBackground(java.awt.Color.lightGray);
        jtfTDC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblDateTime5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime5.setText("Date :");

        jtfDate.setEditable(false);
        jtfDate.setBackground(java.awt.Color.lightGray);
        jtfDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Delivery Report");

        jlblDateTime1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDateTime1.setText("Staff ID :");

        jbtnCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnCheck.setText("Check");
        jbtnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckActionPerformed(evt);
            }
        });

        jlblStaffName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblStaffName.setText("Staff Name :");

        jcbStaffID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Staff ID --", "ST001", "ST002", "ST003", "ST004", "ST005", "ST006" }));
        jcbStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStaffIDActionPerformed(evt);
            }
        });

        jlblStaffName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblStaffName1.setText("KM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTDC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTDC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblDateTime5)
                                .addGap(191, 191, 191)
                                .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblStaffName)
                                    .addComponent(jlblTDT)
                                    .addComponent(jlblDateTime1))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfTDT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlblStaffName1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jbtnCheck)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDateTime1)
                    .addComponent(jcbStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblStaffName)
                    .addComponent(jtfStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTDT)
                    .addComponent(jtfTDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblStaffName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTDC)
                    .addComponent(jtfTDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDateTime5)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jbtnCheck)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckActionPerformed
        if (jcbStaffID.getSelectedItem().equals("ST001")) {
            jtfStaffName.setText("Jack");
            jtfTDT.setText("120");
            jtfTDC.setText("35");
        }
        else if(jcbStaffID.getSelectedItem().equals("ST002")){
            jtfStaffName.setText("Bob");
            jtfTDT.setText("80");
            jtfTDC.setText("20");
        }
        else if(jcbStaffID.getSelectedItem().equals("ST003")){
            jtfStaffName.setText("Dan");
            jtfTDT.setText("100");
            jtfTDC.setText("30");
        }
        else if(jcbStaffID.getSelectedItem().equals("ST004")){
            jtfStaffName.setText("Chris");
            jtfTDT.setText("53");
            jtfTDC.setText("24");
        }
        else if(jcbStaffID.getSelectedItem().equals("ST005")){
            jtfStaffName.setText("Ben");
            jtfTDT.setText("30");
            jtfTDC.setText("16");
        }
        else if(jcbStaffID.getSelectedItem().equals("ST006")){
            jtfStaffName.setText("Brandon");
            jtfTDT.setText("49");
            jtfTDC.setText("18");
        }
    }//GEN-LAST:event_jbtnCheckActionPerformed

    private void jcbStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStaffIDActionPerformed

    }//GEN-LAST:event_jcbStaffIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HR_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HR_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HR_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HR_DailyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HR_DailyReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnCheck;
    private javax.swing.JComboBox jcbStaffID;
    private javax.swing.JLabel jlblDateTime1;
    private javax.swing.JLabel jlblDateTime5;
    private javax.swing.JLabel jlblStaffName;
    private javax.swing.JLabel jlblStaffName1;
    private javax.swing.JLabel jlblTDC;
    private javax.swing.JLabel jlblTDT;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfStaffName;
    private javax.swing.JTextField jtfTDC;
    private javax.swing.JTextField jtfTDT;
    // End of variables declaration//GEN-END:variables
}
